# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-08 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Firstmodel',
            new_name='Post',
        ),
    ]
